name: learnflutterapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.64.0
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.3
  provider: ^6.1.0
  fluttertoast: ^8.2.3
  dots_indicator:
  flutter_screenutil:
  intl: ^0.17.0
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  google_nav_bar: ^5.0.6
  grouped_list: ^5.1.2
  currency_text_input_formatter: ^2.1.8
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/budget.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/budget.png
    - assets/demo_logo1.jpg
    - assets/demo_logo2.png
    - assets/demo_logo3.jpg
    - assets/demo_logo4.jpg
    - assets/user.png
    - assets/password.png
    - assets/expenses.png