// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQyJ083Boubmu-nDRRuvxPNbm4UsSJupA',
    appId: '1:189210396929:web:49b5dfca888c7f97f87300',
    messagingSenderId: '189210396929',
    projectId: 'expensemanagement2023-6d5cf',
    authDomain: 'expensemanagement2023-6d5cf.firebaseapp.com',
    storageBucket: 'expensemanagement2023-6d5cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqoMfJFwQ2Gyps1Gq4BDyxJDdqHDovQbY',
    appId: '1:189210396929:android:0d4de6154936a322f87300',
    messagingSenderId: '189210396929',
    projectId: 'expensemanagement2023-6d5cf',
    storageBucket: 'expensemanagement2023-6d5cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxHSuydvJK7mRuZlVKUeIIRZOukSVQUVw',
    appId: '1:189210396929:ios:8476a90818888e29f87300',
    messagingSenderId: '189210396929',
    projectId: 'expensemanagement2023-6d5cf',
    storageBucket: 'expensemanagement2023-6d5cf.appspot.com',
    iosBundleId: 'com.example.learnflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxHSuydvJK7mRuZlVKUeIIRZOukSVQUVw',
    appId: '1:189210396929:ios:8476a90818888e29f87300',
    messagingSenderId: '189210396929',
    projectId: 'expensemanagement2023-6d5cf',
    storageBucket: 'expensemanagement2023-6d5cf.appspot.com',
    iosBundleId: 'com.example.learnflutterapp',
  );
}
