// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY3cgelWLA_erncHhLZtg2WV-DyH2K1h8',
    appId: '1:1001821187803:web:6587110e3e7857c53326fe',
    messagingSenderId: '1001821187803',
    projectId: 'expensemanagerbloc',
    authDomain: 'expensemanagerbloc.firebaseapp.com',
    storageBucket: 'expensemanagerbloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_wKUYZzUONgtdH_4EDELcx3SGcikOB8',
    appId: '1:1001821187803:android:dd9cb4af2f331de03326fe',
    messagingSenderId: '1001821187803',
    projectId: 'expensemanagerbloc',
    storageBucket: 'expensemanagerbloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL5q_zHhMojD08OGQf61TDnOkn56Lk-dk',
    appId: '1:1001821187803:ios:5d7bf587a25c61a43326fe',
    messagingSenderId: '1001821187803',
    projectId: 'expensemanagerbloc',
    storageBucket: 'expensemanagerbloc.appspot.com',
    iosBundleId: 'com.example.learnflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL5q_zHhMojD08OGQf61TDnOkn56Lk-dk',
    appId: '1:1001821187803:ios:5d7bf587a25c61a43326fe',
    messagingSenderId: '1001821187803',
    projectId: 'expensemanagerbloc',
    storageBucket: 'expensemanagerbloc.appspot.com',
    iosBundleId: 'com.example.learnflutterapp',
  );
}
